### PR TITLE
Add support for vendor extensions and a few other bugfixes.

### PR DESCRIPTION
**Pull request by meuserj**
I'm not sure how active this project is, but I was using it to test the HEP functionality of our software at Genesys. We added some vendor extensions for some of our fields, so I expanded this library to make it easy to define and use such extensions dynamically. In the process I also fixed a few more bugs. There were some spots in the `encapsulate` code that referred to a different field name than the `decapsulate` code used. I also moved away from using `new Buffer(x)` to `Buffer.allocUnsafe(x)` since the former is deprecated.

Feel free to take the changes if you want, but don't feel obligated.

### CODE REVIEW

**Comment by lmangani** [comment]
Hi @meuserj The project is extremely active and used in many of our elements, both CI and Live particularly in the webRTC scope of HEP so thanks for your PR and glad to know HEP is being useful at Genesys - We have a large number of customers monitoring Genesys with our elements so this would surely be of interest! . Could you share more details about your HEP Implementation so we can add it to the covered platforms?

**Comment by lmangani** [comment]
@meuserj could you kindly sign our CLA to allow merging the code?

**Comment by adubovikov** [comment]
@meuserj please sign CLA

**Comment by meuserj** [comment]
Well, I signed it, but my commits did not have an email associated with it when I submitted them, so it isn't recognizing those as being sent by me. I'm not sure how to fix this situation.

**Comment by meuserj** [comment]
Wait.. it had my Genesys email... just a sec, I'll add it to my Github account.

**Comment by lmangani** [comment]
Github probably uses your gmail address but perhaps those were done with a different account? We'll accept it anyhow since you stated it above. 

Any details of this implementation by any chance? We would love to promote HEP adoption.

**Pull request merged**
